#!/usr/bin/env pwsh

# importing data and cleaning into long list (all values in newlines
$Sample = Get-Content -raw $args
# $Sample = Get-Content -delimiter "`n" $args
$data = $Sample.split("`n")
$incr = $null

# $data |get-member
# data[0]


for (($i = 0); $i -lt $data.Length; $i++) {
    [int32[]]$testarr = @(  )
    $data[$i].split(" ") | foreach {$testarr += $_.trim()}
write-host test $i $testarr[$i]
    $len = ($testarr | measure-object -property count)
    $len
    if ($incr -eq $null) {
        $init = ($testarr[$i] - $testarr[($i + 1)])
        if ($init -in (-1..-3)) { $incr = $true
            write-host "init valid, rising" }
        elseif ($init -in (1..3)) {
            $incr = $false
            write-host "init valid, lowering" }
        else {continue}
    }
    for (($j = 0); $j -lt $len; $j++) {
        $diff = $j - ($j + 1)
        if ($incr -eq $true -and $diff -in (-1..-3)) {
            $valid++
            write-host "$i $valid"
            continue }
        elseif ($incr -eq $false -and $diff -in (1..3)) {
            $valid++
            write-host "$i $valid"
            continue }
        else {
            $incr = $null
            break
        }
    if ($valid -eq $len) {
        $final++
        $incr = $null}
    }
}

Write-host "$final are safe!"
